version: "3.8"
services:
  server:
    image: tensorflow/serving
    
    volumes:
      - ./tf_serving_fastapi/model_complete_save_V:/tf_serving_fastapi/model_complete_save_V
      - ./tf_serving_fastapi/training/models.config:/tf_serving_fastapi/training/models.config


    command: '--model_config_file=/tf_serving_fastapi/training/models.config'
    
    ports:
    - '8501:8501'
    

  web:
    image: abzaman/tfsfastapi
   
    
    ports:
    - 80:80

